### ISSUE TITLE
Trying to use API

### ISSUE THREAD

**Issue by ashepherd** [ESIPFed/Semantic-Portal#6]
I'm trying to use the REST API with my API Key but am not finding the right endpoint possibly?

From the documentation (http://data.bioontology.org/documentation) it says the endpoint is at: /search?q={search query}

I tried GET http://ec2-52-23-64-194.compute-1.amazonaws.com/search?q=salinity&apikey=5eeadfbc-9673-4edd-aa82-78ebb26a289 
but that provides HTML. I tried the 'format' parameter as format=json and format=xml which through a 500 response error. And format=jsonp returned HTML. 

I also tried this as a POST, setting request headers:
Authorization: apikey token=5eeadfbc-9673-4edd-aa82-78ebb26a289
Accept: application/json

But also got a 500 response code. 

I think I might not have the endpoint right, possibly? 

The help documentation says there are example REST API scripts here at this github repo, but I found some scripts here instead: https://github.com/ncbo/ncbo_rest_sample_code. It looks like the API does work at http://data.bioontology.org/search

Any ideas on what I'm doing wrong?

**Comment by ashepherd** [comment]
I also tried setting the URL to: http://semanticportal.esipfed.org/search just in case that was the problem

**Comment by ashepherd** [comment]
I figured it out by looking at the annotator JSON link which adds the **:8080** port to access the API. 

This link works:
http://semanticportal.esipfed.org:8080/search?apikey=5eeadfbc-9673-4edd-aa82-78ebb26a2891&q=CTD%20instrument

Suggest updating the documentation or fixing so that port 80 access can be redirected to :8080 if it's possible.

**Comment by linepouchard** [comment]
Thank you Adam.

We'll update the EsIpfed doc.

Line
Sent from my iPhone
Line Pouchard
Brookhaven National Lab

**Comment by pgopavar** [comment]
Updated the documentation to reflect the fact that the portal uses port 8080.

https://github.com/ESIPFed/Semantic-Portal/wiki/Upload-Edit-APIs

Added some python script examples to the documentation.

https://github.com/ESIPFed/Semantic-Portal/tree/master/api_examples

**Comment by linepouchard** [comment]
Thank you Partha.
And congratulations again on your Masters degree
Line

Sent from my iPhone
Line Pouchard
Brookhaven National Lab
