### ISSUE TITLE
Query ontologies via SPARQL

### ISSUE THREAD

**Issue by lewismc** [ESIPFed/Semantic-Portal#7]
Hi @linepouchard is it possible currently to query ontologies, either via a GUI or programmatically with [SPARQL](https://www.w3.org/TR/sparql11-query/)?

**Comment by linepouchard** [comment]
Hi @lewismc The virtual appliance does not include a Sparql endpoint.  
you can query ontologies programmatically via published and documented APIs.

**Comment by lewismc** [comment]
Thank you @linepouchard, for reference the API documentation is available at https://github.com/ESIPFed/Semantic-Portal/wiki

**Comment by MichaelHuhns** [comment]
The Semantic Ontology Portal *does* include a SPARQL endpoint, although it is not at this time supported well.

**Comment by lewismc** [comment]
Hi @MichaelHuhns any documentation you can point me at? I am looking to stream data over HTTP into a portal on a regular basis then query it using SPARQL. The GUI is much less useful for my purposes, thank you.

**Comment by MichaelHuhns** [comment]
Oops, I made a mistake when I claimed that the portal supports a sparql endpoint. It doesn’t. It supports an HTTP GET facility for querying the contents of the portal. The results are returned in Linked Data – JSON format (JSON-LD).

It also supports a PUT that you could use to insert ontology data into the portal.

Sorry about causing confusion!

**Comment by graybeal** [comment]
I think it could support a SPARQL endpoint, since I think AgroPortal does. But some config or work would be required, and performance of the main system could suffer.

Add a second endpoint for an additional fee….

________________________________

**Comment by lewismc** [comment]
ack thank you folks, comments are appreciated
